name: e-commerce

services:
      backend:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: backend
        ports:
            - "8000:8000"
      db:
        image: postgres:16
        container_name: postgres
        environment:
          POSTGRES_PASSWORD : postgres
        ports:
          - "5431:5432"
        volumes:
          - db_data:/data
        
volumes:
  db_data: